name: Daily version check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # 3:00 AM every night

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Detect latest version
        run: |
          FAVA_VERSION=$(curl "https://pypi.org/rss/project/fava/releases.xml" | python3 -c "import sys, re; sys.stdout.write(re.search('<title>([0-9\\.]+)</title>', sys.stdin.read())[1])")
          echo "Latest version: $FAVA_VERSION"
          echo "$FAVA_VERSION" > FAVA_VERSION
          echo "FAVA_VERSION=$FAVA_VERSION" >> ${{ github.env }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: "Update FAVA_VERSION file"
        with:
          commit_message: Bump fava to ${{ env.FAVA_VERSION }}
