name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-10.15
            tag: darwin-amd64
          - os: ubuntu-20.04
            tag: linux-amd64
          - os: [self-hosted, Linux, ARM64]
            tag: linux-arm64
    env:
      FAVA_VERSION: "1.18"
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: fava-${{ env.FAVA_VERSION }}-${{ github.run_id }}-${{ matrix.tag }}
          path: dist
