name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-10.15
            tag: darwin-amd64
          - os: ubuntu-20.04
            tag: linux-amd64
          - os: [ self-hosted, Linux, ARM64 ]
            tag: linux-arm64
    steps:
      - uses: actions/checkout@v2
      - run: echo "FAVA_VERSION=$(cat FAVA_VERSION)" >> ${{ github.env }}
      - name: Build
        run: |
          ./build.sh
          cd dist && zip -r fava-${{ env.FAVA_VERSION }}-${{ github.run_id }}-${{ matrix.tag }}.zip .
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.tag }}
          path: dist/fava-${{ env.FAVA_VERSION }}-${{ github.run_id }}-${{ matrix.tag }}.zip
  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "FAVA_VERSION=$(cat FAVA_VERSION)" >> ${{ github.env }}
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - run: find artifacts
      - uses: ncipollo/release-action@v1
        with:
          artifacts: artifacts/*
          tag: fava-${{ env.FAVA_VERSION }}-${{ github.run_id }}
          body: "Source: https://pypi.org/project/fava/${{ env.FAVA_VERSION }}/"
          token: ${{ secrets.GITHUB_TOKEN }}
